apiVersion: v1
kind: Service
metadata:
  name: pokemons-service
  labels:
    app: pokemons-service
spec:
  type: NodePort
  selector:
    app: pokemons-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
