name: CI/CD Workflow

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run tests
      run: |
        python -m unittest discover -s tests -p '*_test.py'

    - name: Build and push Docker image
      uses: docker/build-push-action@v5.0.0
      with:
        context: .
        push: true
        tags: docker.io/${{ secrets.DOCKERHUB_USERNAME }}/pokemons-service:${{ github.sha }}
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Update Kubernetes manifest
      run: |
        sed -i "s|pokemons-service:latest|pokemons-service:${{ github.sha }}|g" statefulset.yaml

  deploy:
    needs: build_and_push
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up kubectl
      uses: Azure/setup-kubectl@v3

    - name: Apply Kubernetes manifests
      run: |
        kubectl apply -f kubernetes/pv-pvc.yaml
        kubectl apply -f kubernetes/statefulset.yaml
